### ISSUE TITLE
Unable to start on Mac OSX when Python has been installed via Homebrew

### ISSUE THREAD

**Issue by jbergeskans** [GoogleCloudPlatform/composer-local-dev#1]
## Expected Behavior
Local environment successfully starts on command `composer-dev start <local_environment_name>`

## Actual Behavior
Environment fails to start, complaining that bind source path does not exist
```
composer-local-dev git:(main) ✗ composer-dev start local_cc_test                                                           
Starting local_cc_test composer environment...
╭─ Error ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Failed to create container with an error: 400 Client Error for                                                                 │
│ http+docker://localhost/v1.41/containers/create?name=composer-local-dev-local_cc_test: Bad Request ("invalid mount config for  │
│ type "bind": bind source path does not exist:                                                                                  │
│ /opt/homebrew/lib/python3.9/site-packages/composer_local_dev/docker_files/entrypoint.sh")                                      │
│                                                                                                                                │
│ To print debug messages please add --debug flag.                                                                               │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

However, the file exists at the path specified.

## Steps to Reproduce the Problem
1. Install Python via homebrew
2. Create a fresh install of Docker Desktop (w/ default config)
3. Run `composer-dev create --from-image-version composer-2.0.32-airflow-2.3.4 local_cc_test` (or any other valid create command with any version of composer/airflow)
4. Run `composer-dev start <local_environment_name>`

## Fix
Since Docker complies with Apple's sandbox rules, `/opt` isn't available by default. Additionally, it cannot be added through the UI (Settings → Resources → File sharing). The only solution (that I have found) is to manually edit `~/Library/Group\ Containers/group.com.docker/settings.json` and adding `/opt` under `filesharingDirectories`.

The documentation should be updated, noting this issue.

**Comment by piotrwrotniak** [comment]
So it seems you need to use homebrew as well as otherwise python would be installed at eg. `/Library/Frameworks/Python.framework/Versions/3.9/bin/python3`.

**Comment by jbergeskans** [comment]
Ah yeah, that makes sense. Updated reproduction steps and changed the title as well.

**Comment by brandonruhl** [comment]
I am also having this same issue.

**Comment by chriscugliotta** [comment]
I'm getting a similar error, but it's not related to `/opt` prefix.  Instead, the code is seemingly prepending `/host_mnt` to my host mount paths, but no `host_mnt` directory actually exists on my host file system.  I'm running on Apple Silicon.

```bash
(.venv) ccugliotta@macos-F67KWCPVC7 composer-local-dev % composer-dev start my-env-1        
Starting my-env-1 composer environment...
╭─ Error ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Environment failed to start with an error: 400 Client Error for                                                                │
│ http+docker://localhost/v1.41/containers/763db4e16be9fd864432b79c15ca56561b2ad1cae68214d458c405b290624971/start: Bad Request   │
│ ("invalid mount config for type "bind": bind source path does not exist:                                                       │
│ /host_mnt/Users/ccugliotta/Documents/Code/cc-sandbox/test-composer-local-dev/composer/my-env-1/requirements.txt")              │
│                                                                                                                                │
│ To print debug messages please add --debug flag.                                                                               │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by piotrwrotniak** [comment]
We've added a handling for this case and extended documentation (Homebrew/docker not having access to CLI installation path). 

@chriscugliotta could you please open separate issue if this is still unresolved.
