### ISSUE TITLE
Cannot access `data` folder on local composer env

### ISSUE THREAD

**Issue by toandm** [GoogleCloudPlatform/composer-local-dev#11]
**What I want to do:** On Cloud Composer, after uploading my file `my_config.yaml` to the `data` folder in GCS bucket, I can access the file on DAGs at the path `/home/airflow/gcs/data/my_config.yaml` . I want to do the same on the composer dev environment

**Blocker**: However, after setting up my local composer environment, there are DAG import error saying `FileNotFoundError: [Errno2] No such file or directory: '/home/airflow/gcs/data/my_config.yaml'`

**Debug:** I tried to go into the running composer-dev docker container to see the folder structure
* List running containers with `docker ps`
* Go into the running composer-dev container with `docker exec -it <composer-dev container name> bash`

Turns out the `data` folder is mapped to `/home/airflow/airflow/data` instead of `/home/airflow/gcs/data`. Folders `dags` and `plugins` are mapped correctly, but not `data`.

**Suggestion:** Please correctly map the `data` folder to `/home/airflow/gcs/data` like mentioned on [Cloud Composer docs](https://cloud.google.com/composer/docs/composer-2/cloud-storage#folders_in_the_bucket).

**Comment by piotrwrotniak** [comment]
Thanks for reporting, we will fix this shortly.
