### ISSUE TITLE
KubernetesPodOperator is not supported currently -> needs kubeconfig

### ISSUE THREAD

**Issue by kirajano** [GoogleCloudPlatform/composer-local-dev#14]
As per current setup, the local credentials are not mounted and have to be somehow manually copied. The file `~/.kube/config` is not mounted and hence inside the container you cannot interact with K8S clusters.  Solution is needed to make K8s workloads testable in Airflow.

Opened PR #15 please feel free to check

**Comment by piotrwrotniak** [comment]
I think one can always use mounted GCP credentials to retrieve GKE cluster kubeconfig by invoking gcloud: `https://cloud.google.com/sdk/gcloud/reference/container/clusters/get-credentials`.

I'm not sure whether we want to expose any additional credentials stored locally to the running Composer Local Environment, let me get back on this to you.

**Comment by kirajano** [comment]
Thanks for you reply,
The suggestion makes sense if your run only GKE clusters but for others you have to then manually make additional setup. In addition, you already have your local `config` with aliases, preferences etc. already there. Fetching credentials from GCP would then be creating a new `config` from scratch - although this is really more about convenience.

Looking forward to your verdict.

**Comment by fpopic** [comment]
> I think one can always use mounted GCP credentials to retrieve GKE cluster kubeconfig by invoking gcloud: https://cloud.google.com/sdk/gcloud/reference/container/clusters/get-credentials.

@piotrwrotniak it would be nice to either provide support to add custom docker volume mounts or support the [airflow to K8s auth order](https://airflow.apache.org/docs/apache-airflow-providers-cncf-kubernetes/stable/connections/kubernetes.html#:~:text=Use%20kube_config%20that%20reside%20in%20the%20default%20location%20on%20the%20machine(~/.kube/config)%20%2D%20just%20leave%20all%20fields%20empty) as-is without the need for additional setup, the same way ADC works for gcloud auth without any intervention within the container.

**Comment by msgongora** [comment]
> I think one can always use mounted GCP credentials to retrieve GKE cluster kubeconfig

@piotrwrotniak What if you use a local cluster through minikube, Docker Desktop, etc? Aren't we talking about local development? This is a legit issue.

**Comment by fpopic** [comment]
Hi @piotrwrotniak, any update or any estimation when issues/PRs in this repository are getting some attention?

**Comment by michalmodras** [comment]
The way forward we'll be supporting custom mounts - we'll be working on this (Cloud Composer).

**Comment by mbaltrusitis** [comment]
@michalmodras do you know when you can expect an update?

**Comment by ahidalgob** [comment]
See https://github.com/GoogleCloudPlatform/composer-local-dev/pull/15#issuecomment-2208777418, it will be included in the next release
