### ISSUE TITLE
-use-feature=2020 fails installation

### ISSUE THREAD

**Issue by Ohadbasan** [GoogleCloudPlatform/composer-local-dev#16]
Hello! I am using version 0.9.1 of composer-dev

my requirements file contains one pypi package: apache-airflow-providers-google

when resetting my env I am getting an error:

023-03-16T09:29:28.563970262Z ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.
2023-03-16T09:29:28.563996804Z
2023-03-16T09:29:28.564003304Z We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.
2023-03-16T09:29:28.564005762Z

thank you!

**Comment by piotrwrotniak** [comment]
Hey,

Composer Local Development CLI uses Composer images that come with this package.

To see preinstalled packages please see: https://cloud.google.com/composer/docs/concepts/versioning/composer-versions#images
