### ISSUE TITLE
Loosen google-auth allowed versions

### ISSUE THREAD

**Issue by steve148** [GoogleCloudPlatform/composer-local-dev#17]
# Description

This week I was playing around with composer-dev to see how it works. As part of this I wanted to see if I could get composer-dev setup as a dev dependency in poetry alongside the other dependencies I would use when working on airflow locally. After figuring out most of the dependency conflicts, I was stuck on one related to `google-auth`. Looking at the source code here for composer-dev, I saw the following in the `install_requires`.

https://github.com/GoogleCloudPlatform/composer-local-dev/blob/89c54a5728964678f87e6570a2c4d7eed7eff8f1/setup.py#L28

Looking around the rest of the code, it's not clear why this dependency is restricted to only v1.30. It seems like the main thing used from the dependency is some exceptions which I believe exist in newer versions as well.

If google-auth can be loosened to include versions greater than 1.30, that would make it way easier for anyone using the project to get this setup alongside their other dependencies they use in Composer. If it would help I can make that change and test it out as well.

**Comment by ahidalgob** [comment]
Current supported version was bumped to `google-auth==2.27.*`
