### ISSUE TITLE
DAG/plugins/data path is different from GCP Cloud Composer

### ISSUE THREAD

**Issue by dan0dbfe** [GoogleCloudPlatform/composer-local-dev#2]
First of all, thanks for creating this tool. The local environments will come in very useful for local testing, shortening the feedback loop.

I noticed that my DAGs were failing because:

* Data path in the local Airflow environment: `/home/airflow/airflow/data`
* Data path in GCP Cloud Composer: `/home/airflow/gcs/data`

Please consider making the paths the same so that absolute path references work.

This is useful for BashOperator's `cwd` argument, which is non-templated and needs an absolute path.

## Workaround
```bash
ln -s /home/airflow/airflow/dags /home/airflow/gcs
ln -s /home/airflow/airflow/plugins /home/airflow/gcs
ln -s /home/airflow/airflow/data /home/airflow/gcs
```

You may modify the CLI to add this in `entrypoint.sh` too.

Thank you!

**Comment by piotrwrotniak** [comment]
Since we're in 0.9.x version we've made a decision to align the paths so the workaround is not needed anymore.

Thanks for reporting this discrepancy :)
