### ISSUE TITLE
Airflow can't access env variables

### ISSUE THREAD

**Issue by VictorValar** [GoogleCloudPlatform/composer-local-dev#27]
I've followed the documentation and added environment variables to variables.env but the variables don't show up when I run:
``` bash
composer-dev run-airflow-cmd ENV_NAME variables list
```
I have restarted and even removed the docker container but the variables don't update.
The only workaround I've found is to manually set the variables via the UI.

**Comment by aflansburg** [comment]
I also randomly started encountering this issue. Variables set in `variables.env` are set in the Docker composer-local-dev container, but unable to retrieve them with the above command or the `get()` method of `airflow.models.variable`
