### ISSUE TITLE
When running on Linux, can't read `application_default_credentials.json` to access gcloud resources

### ISSUE THREAD

**Issue by dan0dbfe** [GoogleCloudPlatform/composer-local-dev#3]
`[Errno 13] Permission denied: '/home/airflow/.config/gcloud/application_default_credentials.json'`

## Cause
The file is present but the UID of the logged-in user (typically `1000`) differs from the UID of the `airflow` user (`999`) in the container. Airflow will not have permission to read the file to access GCP resources with it.

It's the typical Docker-Linux UID/GID mismatch problem when bind mounting directories. (Mac, Windows use network file transfers in the background instead since Docker there runs off a Linux VM.)

## Workaround
Run `chmod +r ~/.config/gcloud/application_default_credentials.json` on your machine.

However other users on the machine now can read this file. This is potentially insecure.

## Proposed Fix
~Include `gcloud_config_path` in `fix_file_permissions()`~

* Copy `~/.config/gcloud` into the container and `chmod +r` instead of volume mounting
* Or set UID/GID to the currently logged-in user when starting the container. This also fixes permissions for the `data`/`dags`/`plugins` directories where the `airflow` user can't modify files written by the user and the user can't modify or read files written by `airflow`.

**Comment by piotrwrotniak** [comment]
Thanks for reporting, we are working on aligning UUIDs of the host/in container user.

**Comment by ivan-toriya-precis** [comment]
+1
Any updates on this one?

**Comment by functicons** [comment]
Can this issue be closed? @ahidalgob

**Comment by ahidalgob** [comment]
@functicons I will merge it into main and then we can close it. Thanks for working on this!

**Comment by ivan-toriya-precis** [comment]
Hey @ahidalgob!
Can you please merge it? We still experience the same issue with `Permission denied`

**Comment by nbonnotte** [comment]
Hello :wave: 
Thank you so much for such a nice tool. I'm experiencing the same issue. Any update on when it will be merged to main? :pray: 
Thank youuu :bow:

**Comment by nbonnotte** [comment]
Actually, the solution provided by #24 does not work for me. I can start the Composer dev and it works fine... the first time. But if I stop it and start it again, the container quickly dies. The logs show this error
```
+ pip3 install --upgrade -r composer_requirements.txt
WARNING: The directory '/home/airflow/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/home/airflow/.local/lib'
Check the permissions.
```

I think all the commands in the `init_airflow` function should be run as `sudo`.

Also, as a side effect of using `sudo`, some envrionment variables (such as `ENV`) disappear :cry:

**Comment by gust-p** [comment]
This is marked as completed but still happening...
