### ISSUE TITLE
Outdated google auth causing local issues

### ISSUE THREAD

**Issue by justinaugust** [GoogleCloudPlatform/composer-local-dev#33]
https://github.com/GoogleCloudPlatform/composer-local-dev/blob/89c54a5728964678f87e6570a2c4d7eed7eff8f1/setup.py#L28

Needs to be upgraded. `2.27.*` works

**Comment by nbonnotte** [comment]
Issue raised in #32 already :wink:

**Comment by daniel-bartley** [comment]
Would renovatebot / dependabot / google equivalent be a simple long term solution to the outdated dependencies?

**Comment by kbenzakri-lelp** [comment]
> https://github.com/GoogleCloudPlatform/composer-local-dev/blob/89c54a5728964678f87e6570a2c4d7eed7eff8f1/setup.py#L28
> 
> Needs to be upgraded. `2.27.*` works

 Indeed, it worked for me with this version.

**Comment by ahidalgob** [comment]
Fixed in version 0.9.2
