### ISSUE TITLE
Python 3.11

### ISSUE THREAD

**Issue by nbonnotte** [GoogleCloudPlatform/composer-local-dev#34]
The [latest release of Composer](https://cloud.google.com/composer/docs/concepts/versioning/composer-versions) uses Python 3.11, which is great news. It would be awesome if this project could be compatible with 3.11 as well :sweat_smile:

**Comment by michalmodras** [comment]
We're working on it.

**Comment by ahidalgob** [comment]
Fixed on version 0.9.2
