### ISSUE TITLE
Composer won't start again when COMPOSER_CONTAINER_RUN_AS_HOST_USER 

### ISSUE THREAD

**Issue by nbonnotte** [GoogleCloudPlatform/composer-local-dev#47]
I'm using the latest version (eacc17c2c934b7873b7302f4d6b2dd9bdaf6d9d8).

The first time Composer starts, everything is working fine. But if I stop it, and start it again, it doesn't work any more. Here are the final logs the container gives:

```
$ docker container logs composer-local-dev-my-composer 
...
+ run_airflow_as_host_user
+ create_user nicolas 1000
+ local user_name=nicolas
+ local user_id=1000
+ local old_user_name
+ whoami
+ old_user_name=airflow
+ local old_user_id
+ id -u
+ old_user_id=999
+ echo Adding user nicolas(1000)
+ sudo useradd -m -r -g airflow -G airflow --home-dir /home/airflow -u 1000 -o nicolas
Adding user nicolas(1000)
useradd: user 'nicolas' already exists
```

**Comment by ahidalgob** [comment]
Hi @nbonnotte, all fixes were merged into the development branch, right? we will realease a new version soon.

If something is missing please reopen this issue.
