### ISSUE TITLE
Docker not available or failed to start after new version of requests

### ISSUE THREAD

**Issue by nbonnotte** [GoogleCloudPlatform/composer-local-dev#55]
Today `composer-dev` failed to start with a message 
>  Docker not available or failed to start. Please ensure docker service is installed and running.

It seems to come from the recent release of requests 2.32. It is a bug in the docker python library that is already traced, see https://github.com/docker/docker-py/issues/3256

Pinning requests to a previous version solves the issue

**Comment by GabrielBoninUnity** [comment]
same issue! pinning requests to version 2.31 in the dependency in setup.py is fixing the issue 

dependencies = [
    "click>=7.0",
    "google-auth==2.27.*",
    "google-cloud-orchestration-airflow>=1.2.0",
    "google-cloud-artifact-registry>=1.2.0",
    "rich_click==1.4.0",
    "docker==6.*",
    "requests==2.31.*"
]

**Comment by nbonnotte** [comment]
Alternatively, we can bump the version of `docker` following the release of `7.1.0`. I have opened a PR #57 57

**Comment by giuseppe-russo** [comment]
same issue, is it possible to merge that PR ? Thanks

**Comment by ivan-toriya** [comment]
Pinning docker to 7.1.0 doesn't work for me.
Same error.

```log
                    DEBUG    docker.utils.config:Trying paths: ['/home/ivan/.docker/config.json', '/home/ivan/.dockercfg']                                      config.py:21
                    DEBUG    docker.utils.config:Found file at path: /home/ivan/.docker/config.json                                                             config.py:25
                    DEBUG    docker.auth:Found 'credsStore' section                                                                                              auth.py:177
                    DEBUG    root:Docker not found.                                                                                                       environment.py:470
```

**Comment by ahidalgob** [comment]
Fixed in https://github.com/GoogleCloudPlatform/composer-local-dev/pull/74
