### ISSUE TITLE
DockerException: Error while fetching server API version: Not supported URL scheme http+docker

### ISSUE THREAD

**Issue by feelingsonice** [GoogleCloudPlatform/composer-local-dev#61]
On `main` after `pip install .` and running `composer-dev create`, got the error:

```
DockerException: Error while fetching server API version: Not supported URL scheme http+docker
```

Looks like this is related to https://github.com/docker/docker-py/issues/3256

**Upgrading to `docker==7.1.0` inside `setup.py` and reinstalling fixed the issue for me.**

Context:

```
pip 24.1.1 
python 3.10
```

**Comment by rishi-aga** [comment]
we can add `"requests==2.31.0",` in setup.py

**Comment by gust-p** [comment]
> we can add `"requests==2.31.0",` in setup.py

This solved my issue. Thanks.

**Comment by cbeauch** [comment]
I followed this but still getting the same error. Any ideas?

**Comment by ralbritton-utah** [comment]
I made both adjustments to the `setup.py`, changing from docker 6.* to 7.* and added the "requests==2.31.0" to the dependencies and this resolve the error.

**Comment by ahidalgob** [comment]
Fix merged into the development branch, a new version will be released soon with this and more fixes/improvements. Use the development branch meanwhile if needed.
