### ISSUE TITLE
Segmentation Fault Error when Creating Environment

### ISSUE THREAD

**Issue by ralbritton-utah** [GoogleCloudPlatform/composer-local-dev#65]
When running the command to create a new composer environment I receive `Segmentation Fault` instead of a success message. 

I did have to modify the `setup.py` to increase the docker version to 7.x and I also added `requests==2.31.0` to the dependencies list per [this suggestion](https://github.com/GoogleCloudPlatform/composer-local-dev/issues/61) to resolve a seperate error.  I've read that this can be a memory error. I've closed all apps running on my laptop except for the cli and VS Code. 

My system

- 16GB of RAM
- Windows 11, 64-bit.
- python 3.11
- Docker Desktop 4.34.0

**Comment by ahidalgob** [comment]
docker version is bumped to 7 in the development branch. A new version will be released soon with this and more fixes/improvements. Use the development branch meanwhile if needed.
