### ISSUE TITLE
Support for arm64

### ISSUE THREAD

**Issue by kalona** [GoogleCloudPlatform/composer-local-dev#67]
Hi,

Is there support for arm64 architecture?
 I am getting this error when the container is started:
 
 exec /usr/bin/sh: exec format error

Thanks,
Kiril

**Comment by ahidalgob** [comment]
Hi, at the moment we don't have plans of providing images for different architectures - the public tracking issue for this is https://issuetracker.google.com/issues/277154322.

It should be possible to currently run the tool using Rosetta if you are on Apple M1,M2,etc.
