### ISSUE TITLE
Error in composer-dev setup command: 'install_requires' must be a string of lists

### ISSUE THREAD

**Issue by madsemildahlgaard** [GoogleCloudPlatform/composer-local-dev#7]
Hi!

I get the following error when running `pip install .` 

```
Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      error in composer-dev setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
          google-cloud-orchestration-airflow>=1.2.*
                                            ~~~~~^
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Python version: `Python 3.10.8`
Pip version: `pip 22.2.2`

**Comment by zachary-povey** [comment]
I'm getting the same on macos with:

`python: 3.8.10`
`pip: 23.0`
`setuptools: 67.1.0`

and 

`python: 3.11.1`
`pip: 22.3.2`
`setuptools: 67.1.0`

**Comment by hejnal** [comment]
Same here: 

python: 3.10.3
pip: 23.0

**Comment by hejnal** [comment]
It worked when removing the * in the dependency definition:

e.g.
    "google-cloud-orchestration-airflow>=1.2.0",
    "google-cloud-artifact-registry>=1.2.0"

But I'm not sure if that's a valid workaround, and not sure why the * wildcard does not work in this context..

**Comment by pawel-wiszniewski** [comment]
Same problem. MacOS, pyenv environment:

Python 3.8.12
pip        23.0
setuptools 56.0.0 and 67.2.0
