### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by fgmehlin** [GoogleCloudPlatform/composer-local-dev#76]
It looks like this doesn't support newer Python versions (3.12+), and I think as well newer Docker versions.

Is the project still maintained and are there plans to ship an update soon?

Thanks!

**Comment by ahidalgob** [comment]
Hi, a new version should be released soon including several updates and fixes. Nonetheless Composer uses Python 3.11, so support for Python 3.12+ is not a priority for the local-dev tool for the moment.

**Comment by sujeeth62** [comment]
@ahidalgob - Is it possible to have version package for python. Also, is this available on PyPI ?

**Comment by ahidalgob** [comment]
@sujeeth62 this is not planned for now, the expected workflow is to install it with `pip install .` after cloning the repo. If you think a pypi package would bring benefits please open a new ticket with the reasons and we will consider it. Thank you!
